name = "drive"
type = "webpack"
workers_dev = true
account_id = "226c0d908704626c8e9c995233a4dd2f"
zone_id = "820e287c1092858fe72133f8b1b82ffa"
kv_namespaces = [
    { binding = "BUCKET", id = "3c60b0a597bd40699ee7b5d9adea95b5" }
]

[env.staging]
name = "drive-staging"
